services:
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - "3001:80"
    environment:
      - VITE_API_URL=http://api:3004
    depends_on:
      - api

  blog:
    build:
      context: .
      dockerfile: apps/blog/Dockerfile
    ports:
      - "3002:3000"
    environment:
      - VITE_API_URL=http://api:3004
    depends_on:
      - api

  storefront:
    build:
      context: .
      dockerfile: apps/storefront/Dockerfile
    ports:
      - "3003:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3004
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "3004:5001"
    environment:
      - NODE_ENV=development
      - PORT=3004

  ui:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    # UI package is a library, so it doesn't need to be exposed 