name: repo-prod

services:
  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - "5001:80"
    environment:
      - VITE_API_URL=http://api:5003
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  storefront:
    build:
      context: .
      dockerfile: apps/storefront/Dockerfile
    ports:
      - "5002:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:5003
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "5003:5001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ui:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    ports:
      - "5006:80"
    environment:
      - PORT=80
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
