services:
  admin-production:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    ports:
      - "5001:80"
    environment:
      - VITE_API_URL=http://api:5004
    depends_on:
      - api-production

  blog-production:
    build:
      context: .
      dockerfile: apps/blog/Dockerfile
    ports:
      - "5002:3000"
    environment:
      - VITE_API_URL=http://api:5004
    depends_on:
      - api-production

  storefront-production:
    build:
      context: .
      dockerfile: apps/storefront/Dockerfile
    ports:
      - "5003:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://api:5004
    depends_on:
      - api-production

  api-production:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "5004:5001"

  ui-production:
    build:
      context: .
      dockerfile: packages/ui/Dockerfile
    # UI package is a library, so it doesn't need to be exposed