services:
  repo-dev-base:
    build:
      context: .
      dockerfile: Dockerfile.dev.base
    volumes:
      - .:/app:cached
      - ~/.ssh:/root/.ssh:ro
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
    command: sleep infinity
    environment:
      - NODE_ENV=development
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    x-develop:
      watch:
        - action: rebuild
          path: .

  admin:
    depends_on:
      - repo-dev-base
    build:
      context: .
      dockerfile: apps/admin/Dockerfile.dev
    ports:
      - "3001:80"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app:cached
    x-develop:
      watch:
        - action: rebuild
          path: .

  blog:
    depends_on:
      - repo-dev-base
    build:
      context: .
      dockerfile: apps/blog/Dockerfile.dev
    ports:
      - "3002:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app:cached
    x-develop:
      watch:
        - action: rebuild
          path: .

  storefront:
    depends_on:
      - repo-dev-base
    build:
      context: .
      dockerfile: apps/storefront/Dockerfile.dev
    ports:
      - "3003:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app:cached
    x-develop:
      watch:
        - action: rebuild
          path: .

  api:
    depends_on:
      - repo-dev-base
    build:
      context: .
      dockerfile: apps/api/Dockerfile.dev
    ports:
      - "3004:5001"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app:cached
    x-develop:
      watch:
        - action: rebuild
          path: .
