[test]
# Enable DOM environment for React tests
preload = ["../test-preset/happydom.ts", "../test-preset/testing-library.ts", '../test-preset/test-setup.ts']
env = { NODE_ENV = "test" }

# Test timeout in milliseconds
timeout = 5000

# Enable coverage reporting
coverage = true 

# Exclude test-preset files from coverage reporting
coveragePathIgnorePatterns = [
	"**/test-preset/**",
	"**/node_modules/**",
	"**/dist/**",
	"**/build/**",
	"**/.turbo/**",
	"**/coverage/**"
]