name: Common Setup

on:
  workflow_call:
    inputs:
      fetch-depth:
        description: 'Number of commits to fetch'
        required: false
        type: string
        default: '0'
      ref:
        description: 'Branch or commit to checkout'
        required: false
        type: string
        default: '${{ github.ref }}'
    outputs:
      cache-hit:
        description: 'Whether the cache was hit'
        value: ${{ jobs.setup.outputs.cache-hit }}

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.bun-cache.outputs.cache-hit }}
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}
          ref: ${{ inputs.ref }}

      - name: 🚀 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.11

      - name: 🗃️ Cache Bun dependencies
        uses: actions/cache@v4
        id: bun-cache
        with:
          path: |
            ~/.bun/install/cache
            **/node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: 📦 Install dependencies
        if: steps.bun-cache.outputs.cache-hit != 'true'
        run: |
          bun install -E --no-save
          bun install -g --frozen-lockfile @biomejs/biome@2.0.0-beta.2
          bun install -g --frozen-lockfile turbo@2.5.3
          bun install -g --frozen-lockfile @changesets/cli@2.29.3 